version: '3.8'
services:
  backend:
    build: .
    working_dir: /app/backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
    ports:
      - "3000:3000"
    command: npm run dev --prefix ./backend

  frontend:
    image: node:18-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install --prefix ./frontend && npm run dev --prefix ./frontend -- --host 0.0.0.0"
